name: Fetch Repo Stats

on:
    schedule:
        # Run this once per day, towards the end of the day for keeping the most
        # recent data point most meaningful (hours are interpreted in UTC).
        - cron: '0 23 * * *'
    workflow_dispatch: # Allow for running this manually.

jobs:
    j1:
        name: store-repo-stats
        runs-on: ubuntu-latest
        steps:
            - name: run-ghrs
              uses: jgehrcke/github-repo-stats@RELEASE
              with:
                  ghtoken: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
